name: vapecommander_rewards_client
description: A Dart client to interact with the vapecommander_rewards Solana program
version: 0.1.0

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  json_annotation: ^4.8.1
  crypto: ^3.0.3
  pointycastle: ^3.7.3
  http: ^1.1.0

dev_dependencies:
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  lints: ^2.1.0
  test: ^1.21.0